image: Visual Studio 2017

environment:
  PYTHON: C:\Python36-x64

init:
  - git config --global core.autocrlf true

  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq 'true') {
          $tagName = $env:APPVEYOR_REPO_TAG_NAME -replace "^v", ""
          Update-AppveyorBuild -Version "$tagName.$env:APPVEYOR_BUILD_NUMBER"
      }

install:
  - git submodule update --init --recursive

build_script:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - python --version
  - python build.py

artifacts:
  - path: build\x64\Release\*.dll
    name: DLL only
  - path: build\*.zip
    name: Packaged

deploy:
  - provider: GitHub
    auth_token:
      secure: lxxfA9UGPnXKXt3aGCdOmc3pkx7jNl7vaBVA215soTHb5cb55hBJ2ZReW2cmMLcQ
    artifact: DLL only
    draft: false
    force_update: true
    on:
      appveyor_repo_tag: true
